### ISSUE TITLE
Bug list out of date

### ISSUE THREAD

**Issue by scop** [fedora-infra/fedora-packages#176]
https://apps.fedoraproject.org/packages/kid3/bugs/all says "This package has no bugs - go file some!!!" but there is https://bugzilla.redhat.com/show_bug.cgi?id=1267562 open roughly a day now.

**Comment by ralphbean** [comment]
I think you just hit the cache.  (which should've been updated shortly after you visited the page).

**Comment by scop** [comment]
Yeah, that was kind of implicit. The point of this bug report is that if the cache updates once a day (the bug had been open for roughly a day) it's much too infrequent, and if it's supposed to update more frequently, it did not. Which of these is it?

**Comment by ralphbean** [comment]
It updates only when accessed.

- So, when you access it the very first time, it takes a long time to load and presents you with fresh data.
- The next time you access it, it shows you the same data as last time, but if it has been more than (some very short time... five minutes maybe?) it asynchronously goes out and gets fresh data so that...
- The *next* time you access it, you will have the latest data.

**Comment by ralphbean** [comment]
OK, [a rewrite is now deployed](http://threebean.org/blog/history-of-fedora-packages/) and this bug seems to be fixed.  Please open a new one if you notice things getting squirrely again.
