### ISSUE TITLE
Active Releases Overview not show F28 status 

### ISSUE THREAD

**Issue by sergiomb2** [fedora-infra/fedora-packages#356]
Subject says all , for when F28 status  ?

**Comment by cverna** [comment]
Currently the Release Overview shows only the Released Version (currently F26 and F27)  this is because we get the releases from [bodhi](https://bodhi.fedoraproject.org/releases/) `current` list. This needs to be changed to include the bodhi `pending` release. 

We should look here to fix this issue https://github.com/fedora-infra/fedora-packages/blob/develop/fedoracommunity/search/index.py#L107
